### ISSUE TITLE
老哥你好，从你思否的网络请求文章过来的，请问能留个联系方式沟通交流吗？我对网络请求这块不大熟悉，想跟老哥探讨下

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [lindroy/NetworkRequestPractice#7]

**Comment by lindroy** [comment]
请问是哪里不明白的呢？可以详细说说。

**Comment by SaltedFish-Extreme** [comment]
> 请问是哪里不明白的呢？可以详细说说。

比如我想把请求的状态回调在全局配置下，用扩展函数写两个适配，一个是页面初始化请求数据渲染页面的时候，开始进度条加载，完成隐藏进度条，成功渲染数据，失败用一个图片来代替本该显示的页面，第二个就是recyclerView加载更多的时候，封装一下BaseRecyclerViewAdapterHelper这样的三方框架，这样大部分的情况只需要用发起请求的方法.扩展函数就能使用，这样在函数体里只需要重写成功的回调就可以了，还有我不知道只用协程和retrofit应该怎样简单的发起网络请求，不想使用ViewModel和LiveData

**Comment by lindroy** [comment]
1. 你说的这个其实就是缺省图吧？加载动画在页面中的，而不是对话框的形式；
2. 如果不想用 ViewModel 和 LiveData，那就是跟传统的用法一样了，慕课网有个课程可能适合你：[Retrofit网络库](https://www.imooc.com/learn/1000)；也可以去网上搜索一些 Retrofit 的教程。

或者可以加我QQ一起交流讨论：1603683935。

**Comment by SaltedFish-Extreme** [comment]
> 

好的，麻烦老哥了
