### ISSUE TITLE
接口为什么会请求两次

### ISSUE THREAD

**Issue by huqiyu** [lindroy/NetworkRequestPractice#9]
一个接口会请求两次

**Comment by lindroy** [comment]
哪个分支的呢？我看看。

**Comment by huqiyu** [comment]
不好意思,才看到。是dev3.0会有两遍网络请求



在 2022-06-15 12:05:05，"Lindroy" ***@***.***> 写道：

哪个分支的呢？我看看。

**Comment by lindroy** [comment]
> 不好意思,才看到。是dev3.0会有两遍网络请求 在 2022-06-15 12:05:05，"Lindroy" ***@***.***> 写道： 哪个分支的呢？我看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

抱歉，记下了，但最近比较忙，周末看看。

**Comment by lindroy** [comment]
> 不好意思,才看到。是dev3.0会有两遍网络请求 在 2022-06-15 12:05:05，"Lindroy" ***@***.***> 写道： 哪个分支的呢？我看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

已经修复了，谢谢指正。
